### ISSUE TITLE
In-app shortcut cheatsheet

### ISSUE THREAD

**Issue by samiebee43** [WasatchPhotonics/ENLIGHTEN#109]
Working on issue #88 I discovered some of the existing shortcuts for the first time.

For instance Ctrl+1 and Ctrl+2 switch between Scope and Settings. Knowing these shortcuts would have been very helpful for plugin development which often involves frequent switching between these views.

I think it would make sense to advertise these shortcuts to our users via the GUI itself. Here's how some other programs accomplish this.

Google drive
<img width="464" alt="image" src="https://user-images.githubusercontent.com/124081765/220665481-4e0da9ce-7a66-43b2-a6cf-6acc70612eee.png">
CMD+/ (mac) or "Help>Keyboard shortcuts" reveals the shortcut actions.

Visual Studio Code
![image](https://user-images.githubusercontent.com/124081765/220665978-aa258579-97b7-430a-b3b8-1c7121347293.png)
Context menus show shortcut keys

Two propose ways to do it in Enlighten.

(1) Show shortcut combos next to buttons
![image](https://user-images.githubusercontent.com/124081765/220667198-eda3d2c2-0572-4fb7-a85f-61ce20271c83.png)

(2) Use dedicated Marquee space (to be added in #92) for a shortcuts cheatsheet button.
![image](https://user-images.githubusercontent.com/124081765/220669979-298199c3-4037-4bdc-accb-f3b3871dbab8.png)
Clicking this button would present all of the shortcuts at once.

**Comment by samiebee43** [comment]
![image](https://user-images.githubusercontent.com/124081765/220704989-cb26f339-f598-43c8-8447-726b519c9fe5.png)
 Some buttons have tooltips as @mzieg pointed out.
Perhaps these can be added to the Scope,Settings,Hardware,Log dropdown

**Comment by mzieg** [comment]
> Show shortcut combos next to buttons
> shortcuts cheatsheet button

I like 'em both :-)  All about supporting multiple learning styles...

**Comment by mzieg** [comment]
![image](https://github.com/WasatchPhotonics/ENLIGHTEN/assets/2125705/5d3a4ef3-2d36-498b-97a6-29220d85f527)
![image](https://github.com/WasatchPhotonics/ENLIGHTEN/assets/2125705/cfe7e68a-d4fd-433e-97c5-191291686f30)
![image](https://github.com/WasatchPhotonics/ENLIGHTEN/assets/2125705/b7dcc5ee-5728-4d49-9906-1075460297f9)

**Comment by mzieg** [comment]
also addressed in #214
