### ISSUE TITLE
HROI eeprom r/w

### ISSUE THREAD

**Issue by samiebee43** [WasatchPhotonics/ENLIGHTEN#119]

**Comment by mzieg** [comment]
Can you expand on that?
![image](https://github.com/WasatchPhotonics/ENLIGHTEN/assets/2125705/00749a20-ac5e-4d1f-8d45-86305ce0769e)

**Comment by samiebee43** [comment]
This comment came to be in passing while I was working on something else. I was doing several things at once at the time, so I'm surprised I had a chance to write it down.

All I know was that this was flagged as an area of interest around March 28th. And whomever mentioned must've confirmed they were using a late version of Enlighten, otherwise I wouldn't have logged it without more details.

Since we have another issue like this (#112), where it's unclear how to detect if the issue is still present. We should consider closing both as not planned for the sake of organizational simplicity (After testing save wavecal). We can then reopen issues if we discover them with detailed reproduction steps.
