### ISSUE TITLE
Low-priority: consider audible feedback when laser firing

### ISSUE THREAD

**Issue by mzieg** [WasatchPhotonics/ENLIGHTEN#122]
Rudimentary support is provided for this, but only when the laser starts firing, and stops firing.  Useful audible feedback should ideally loop while the laser is firing, similar to visible LEDs / indicators.

**Comment by samiebee43** [comment]
For indefinite length audio, tone generation is the way to go

```python
import pysine
pysine.sine(frequency=440.0, duration=1.0) 
```

**Comment by mzieg** [comment]
resolved in 4.0.42 I think
