### ISSUE TITLE
LocalBaseline development

### ISSUE THREAD

**Issue by samiebee43** [WasatchPhotonics/ENLIGHTEN#132]
- [x] Center btn --> move plugin.x to vertex-space y-max, gradient ascent
- [x] Use trapezoidal integration
- [x] pandas table --> Measurement/CSV
---
2023-05-08
- [x] independent left and right outer radii (blue)
- [x] remote inner radius (green)
- [x] remove decimals from pandas frame
- [x] add commas to pandas frame
- [x] Use spectra intersection outer radius + linear interpolation for baseline

---

2023-05-11
- [x] Save x-axis units to CSV
- [ ] #181
- [ ] #185
- [ ] #186

**Comment by samiebee43** [comment]
2023-05-08

- [ ] independent left and right outer radii (blue)
- [ ] remote inner radius (green)
- [ ] remove decimals from pandas frame
- [ ] add commas to pandas frame
- [ ] Use spectra intersection outer radius + linear interpolation for baseline
---
- [ ] resizable pandas table
- [ ] move plugin to top of sidebar

**Comment by mzieg** [comment]
I'm unsure if moving to the "very top" of the sidebar is ideal.  Personally I might vote for between (Detector Control, X-Axis) or (X-Axis, Scan Averaging).  I think laser control and detector control (integration time) should remain at the top though.  Making it harder to find (unexpectedly moving) the button to turn off the laser is almost a safety issue.

**Comment by samiebee43** [comment]
Moved checklist items to first comment so this thing is accurate:
![image](https://github.com/WasatchPhotonics/ENLIGHTEN/assets/124081765/645965cd-a9f0-4b36-abd8-b5f9ea6a48f0)

**Comment by samiebee43** [comment]
Was having issues were logging wasn't working. Turns out spec needs to be on for "Process" btn to do anything. Led to the addition of plugins having their own log file, which seems overdue anyway

**Comment by samiebee43** [comment]
Some notes about the current state of this.

When LocalBaseline is enabled and a spec is connected, changing the count clears the widgets.
![image](https://github.com/WasatchPhotonics/ENLIGHTEN/assets/124081765/cd7bda61-180f-4939-a637-8db2760add93)
![image](https://github.com/WasatchPhotonics/ENLIGHTEN/assets/124081765/fce74a35-3c9f-4b47-893b-e95b4bb64fad)

This signifies that immediate-mode widget onchange detection is working and post-config widget spawning is on its way to working. onchange is linked to `reset_configuration` which I think was intended to recreate the layout. It might just be missing a new call to get_configuration_obj. 

Maintaining field contents can be handled at the plugin level. Currently it is only for the `count` parameter which must be persistent for multiplexing to work at all. Persistence of the other fields is an (important) usability improvement.
