### ISSUE TITLE
RamanShiftCorrectionFeature find_peaks FWHM

### ISSUE THREAD

**Issue by mzieg** [WasatchPhotonics/ENLIGHTEN#133]
The 'width' parameter in RamanShiftCorrectionFeature's call to scipy.signal.find_peaks should probably be tied to Spectrometer.fwhm rather than a hardcoded constant for all spectrometers.  (The current implementation has apparently been found to work on all tested units, but it still seems like a design weakness.)

**Comment by mzieg** [comment]
Internal user reported that RamanShiftCorrection was failing on some X-Series units during characterization...this could well be related. Bumping priority.

**Comment by samiebee43** [comment]
Can we get more info about how RamanShiftCorrection is failing?

**Comment by samiebee43** [comment]
And can we make this into a separate issue? You can link them by referencing the issue number. That way I can solve the above reimplement without shadowing a potentially still active bug.
