### ISSUE TITLE
LocalBaseline wishlist

### ISSUE THREAD

**Issue by samiebee43** [WasatchPhotonics/ENLIGHTEN#150]
- [ ] Use Enlighten.xcursor for plugin.x
- [ ] Parabolic estimation peak height
- [ ] Parabolic estimation peak area
- [ ] Run on CSV import
- [x] Slanted Area calculation
- [ ] Show derivative of baseline selector (blue) lines to gauge validity

**Comment by mzieg** [comment]
> Run on CSV import

Note that there is a setting somewhere for "post-process spectra on load", basically to "load" the Raw column and re-process it using current baseline correction, boxcar, peak sharpening etc...and which *should* automatically trigger a currently enabled plugin.

**Comment by mzieg** [comment]
Anecdotal report today that we may have broken area calculation when moving to the independently movable shoulders.

**Comment by samiebee43** [comment]
It was intentionally omitted. Independently movable shoulders came with slanted baseline which changes the area calculation. At the time it was deemphasized for the sake of peak height. Adding it back to wishlist

**Comment by samiebee43** [comment]
With the buzz about this plugin dying down, and the need for plugin refactoring ever present, I think we should close as 'wontfix' for the time being. This particular wishlist deviates from the end-user's requirements. Other things are more pressing.
