### ISSUE TITLE
persistent Fire Laser button

### ISSUE THREAD

**Issue by samiebee43** [WasatchPhotonics/ENLIGHTEN#170]
> I almost wonder if we should think about making the "Fire Laser" button "persistent" in the UI, so it's ALWAYS available (you can always see it glowing bright red when firing, and you can always smash it to turn it off).
>
> You can't always see the scope, so that would disqualify the "button bar" with the graph controls, dark/ref etc.
> 
> Maybe directly beneath VCRControls?  I'm just thinking aloud here...not an immediate action.

_Originally posted by @mzieg in https://github.com/WasatchPhotonics/ENLIGHTEN/issues/155#issuecomment-1579477124_

**Comment by mzieg** [comment]
done in 4.1.0
