### ISSUE TITLE
Save Data location > Change > Cancel > Blank

### ISSUE THREAD

**Issue by samiebee43** [WasatchPhotonics/ENLIGHTEN#180]
![image](https://github.com/WasatchPhotonics/ENLIGHTEN/assets/124081765/64eca447-1266-445b-94ba-ce5603d6c7e8)

The directory label starts out with a path, but it gets cleared if the user clicks change and cancels out of the following folder selection dialog.

**Comment by mzieg** [comment]
Dup of #506
