### ISSUE TITLE
Silence(able) bell from bootstrap.bat

### ISSUE THREAD

**Issue by samiebee43** [WasatchPhotonics/ENLIGHTEN#184]
I most often use bootstrap.bat to activate my environment, which is instantaneous. 
It generates 3 console beeps, which is not practical in my case, though it could be helpful for longer builds.
We can add a second param "--bell" or "--nobell" or omit the bell completely.

This would be a good first issue for new-comers :)

**Comment by mzieg** [comment]
I confess, I added it for building installers so I didn't have to keep the Windows VM onscreen :-)

**Comment by mzieg** [comment]
no plan to fix
