### ISSUE TITLE
Correct MeasurementFactory attribute view -> technique

### ISSUE THREAD

**Issue by samiebee43** [WasatchPhotonics/ENLIGHTEN#198]
> That fixes the bug, but this attribute really shouldn't be called "view" at all. "Absorbance," "Transmission" etc aren't Views (screens), they're spectroscopic techniques. This used to be the case in 3.x (https://github.com/WasatchPhotonics/ENLIGHTEN/blob/3.2.42/enlighten/MeasurementFactory.py#L125), and it was incorrectly changed early in 4.x.

https://github.com/WasatchPhotonics/ENLIGHTEN/commit/526a30b88fcff3cf4616d63f43a8e3b30095a71e#r119708790

**Comment by mzieg** [comment]
Addressed in #223
