### ISSUE TITLE
Measurement > Line 457 > missing assignment

### ISSUE THREAD

**Issue by samiebee43** [WasatchPhotonics/ENLIGHTEN#220]
Line 457 flagged by analyzer. '==' was used instead of '='

That variable is not defined in that case

_Originally posted by @samiebee43 in https://github.com/WasatchPhotonics/ENLIGHTEN/pull/216#discussion_r1251294369_

**Comment by mzieg** [comment]
Hard to tell without context, but if this warning was in expand_template it's probably fixed in #224.

**Comment by samiebee43** [comment]
Confirmed. https://github.com/WasatchPhotonics/ENLIGHTEN/commit/1d574727736e33bbc4032e6669166fd5af4a52c7#r120747000
