### ISSUE TITLE
Consider expanding the diff preimage with Submodules

### ISSUE THREAD

**Issue by samiebee43** [WasatchPhotonics/ENLIGHTEN#246]
## Background

There are two main ways that we can see a difference in Enlighten behavior without seeing a change in code or platform.

Commands like `git diff main 4.0.x --name-only` quickly summarize what happened since the last released revision. Generally variations on diff provide a lot of assistance in debugging, development, and release. Any time that the diff does not fully represent changes in functionality penalizes our process.

The two main ways we can get inconsistent behaviors with a zero diff is (1) due to system state, which is governed by virtual environments and build scripts and (2) diffs within dependencies.

(1) Can be mostly resolved by running the longer running tasks in `bootstrap.bat` to ensure consistent system state. *Currently this aspect is a wontfix*, since it takes a very long time, and costs more than in benefits time-wise. Usually the workflow looks like this:

```bash
run # (< 3 seconds)
# if that fails maybe I'm in an unactivated shell?
scripts/bootstrap.bat activate # (< 5 seconds)
# if that fails maybe UI needs regeneration? (can also check .err to confirm)
scripts/bootstrap.bat ui # (< 15 seconds)
# if that fails (rare), I can rebuild the entire environment
scripts/bootstrap.bat rebuild_env # (< 20 minutes)
```

(2) diffs within dependencies.

One aspect of this are pip and conda dependencies. Generally this includes any 'internet-packages' that we acquire through package manager and do not maintain ourselves. This aspect is encapsulated in #247

Finally, the aspect that this issue is truly about is when one of our own dependencies has a diff that affects Enlighten's behavior. For example a change in Wasatch.PY affects how Enlighten's boxcar works, but if you diff Enlighten you don't see that change.

## The issue

Consider including our own dependencies, such as Wasatch.PY, SpyCWriter, etc using [git submodules](https://git-scm.com/book/ms/v2/Git-Tools-Submodules) which extend the behavior of `diff` to show changes in depended on git repositories. It can also produce some advantages when using shell tools to analyze the repo such as `find` and `grep` -- and it makes it easier to maintain multiple working copies.

## Preimage?

This is an unnecessary nod to mathematical concept that this vaguely resembles. In the mapping of source deltas to runtime deltas, the image of the empty-delta is too large, and reducing the size of that image corresponds to expanding the preimage of non-empty deltas. And somewhat beautifully expanding the preimage is equivalent to expanding the source tree.

## Why only consider?

Last time I thought about git submodules was about 5 years ago, and there have been some changes since then. It's important to ensure that submodules do not introduce more complications than they fix. 

In fact we should only make this change if the repository would remain _usable_ to a novice user of git who only knows git basics such as  `init`, `add`, `commit`, `push`. This is a future-proofing measure. We want to improve the toolset of the experienced git user looking at our repo without non-trivially raising the baseline knowledge required to interact with it.

**Comment by mzieg** [comment]
rejected
