### ISSUE TITLE
Fix logical weirdness of .doing_raman

### ISSUE THREAD

**Issue by samiebee43** [WasatchPhotonics/ENLIGHTEN#286]
See #277. This is about how when you click Raman then click Expert. `.doing_raman` indicates False. Enlighten is written in a way that accommodates that behavior for now, but it would be better if we can say things like `.doing_raman and .expert`.

> Thank you for the comment addition.
> 
> It highlights the strangeness of the or-statement. In the future it would be nice if doing_raman stayed true whenever it is logically selected in the app, but for now that's OK.
> 
> Something like that can be achieved in the future by handling click events something like this
> 
> ```python
> click raman:
>     raman = True
>     nonraman = False
>     expert = False
> click non-raman:
>     raman = False
>     nonraman = True
>     expert = False
> click expert:
>     expert = True
> ```

_Originally posted by @samiebee43 in https://github.com/WasatchPhotonics/ENLIGHTEN/pull/277#pullrequestreview-1631043955_

**Comment by mzieg** [comment]
Believed functioning properly.
