### ISSUE TITLE
High-Gain Mode reported visible on R2 detector?

### ISSUE THREAD

**Issue by mzieg** [WasatchPhotonics/ENLIGHTEN#29]
Investigate and resolve

**Comment by mzieg** [comment]
Per Evan, this was because the spectrometer in question was a custom design which did not map to any of the standard ModelInfo classes in ENLIGHTEN.  We had been defaulting the HighGainModeFeature to visible unless there was a reason to turn it off.  Since there was no ModelInfo instructing us to turn it off, it remained visible.  This logic is being inverted such that the control will default to invisible, unless there is evidence that it should be exposed.

**Comment by rc14193** [comment]
https://github.com/WasatchPhotonics/ENLIGHTEN/pull/33
