### ISSUE TITLE
Improve usability on small screens

### ISSUE THREAD

**Issue by mzieg** [WasatchPhotonics/ENLIGHTEN#298]
<img width="960" alt="image" src="https://github.com/WasatchPhotonics/ENLIGHTEN/assets/2125705/91dd4ab7-b507-438d-8f3f-97b47a446d5c">

(That's 1920x1080 @ 150%, "Dell default")

**Comment by samiebee43** [comment]
What other percentage scales are available on this system? I would defer to that if we can.

Otherwise we may look into UI Scaling as part of Qt. I know GTK has it's own scale parameter. That would prevent having to significantly redesign UI at the moment.

**Comment by mzieg** [comment]
I changed the scale on that laptop to 100%, which made ENLIGHTEN much more usable.

This isn't high-priority, but I feel like relatively minor changes could improve usability in the odd case where we actually are being run at SVGA resolution.  I'm still playing with this in my mind. For instance, if form width < 1024, shrink thumbnail dimensions, maybe overlay Marquee over StatusBar, vertically shrink StatusIndicators etc. More of a journey than a destination, with no firm "hard spec" to reach. Just trying to be considerate to those with constrained resources :-)
