### ISSUE TITLE
Consider moving EnlightenSpectra to /Users/Public/Documents

### ISSUE THREAD

**Issue by mzieg** [WasatchPhotonics/ENLIGHTEN#330]
Maybe this is a long-standing convention, I don't know, but I've been seeing this frequently from other programs and it has some advantages.

**Comment by mzieg** [comment]
I'm not worried about XP support (we only build 64-bit installers, and definitely don't test against XP), but I'm happy to drop the proposal.  We have now considered it :-)

**Comment by samiebee43** [comment]
Thanks. The XP bit was something of a joke. I know we don't actively support it. But still it's one of the best versions of Windows IMO

**Comment by mzieg** [comment]
🎼 Someone just volunteered to support this... 🎵
https://github.com/WasatchPhotonics/Wasatch.VB6
