### ISSUE TITLE
When copying EEPROM to Clipboard, expand all arrays including bad_pixels

### ISSUE THREAD

**Issue by mzieg** [WasatchPhotonics/ENLIGHTEN#348]
Right now, you can't paste these into Excel and be confident the rows will match up, because different lengths of bad_pixels for instance introduce offsets.  (Or pack arrays into space-delimited strings)

**Comment by samiebee43** [comment]
Could you include an example of what the paste currently looks like versus what it should look like in this issue?

**Comment by mzieg** [comment]
Resolved by https://github.com/WasatchPhotonics/ENLIGHTEN/pull/349
