### ISSUE TITLE
Searchable Hardware tab

### ISSUE THREAD

**Issue by mzieg** [WasatchPhotonics/ENLIGHTEN#365]
Add Filter lineedit to Hardware screen, hide rows that don't match regex

**Comment by mpylon** [comment]
I gave this a shot in #391 , @mzieg .

![filter](https://github.com/WasatchPhotonics/ENLIGHTEN/assets/164873743/9abf7419-3f7b-4893-b15e-482ee77c7440)

**Comment by mzieg** [comment]
resolved  by #391
