### ISSUE TITLE
Horizontal ROI toolbar button

### ISSUE THREAD

**Issue by mzieg** [WasatchPhotonics/ENLIGHTEN#41]
Please add button to ENLIGHTEN toolbar allowing Horizontal ROI to be easily enabled / disabled.  If an ROI is configured on the EEPROM, the button should be "on" by default (current behavior).  However, it should be easy to switch the ROI off and on again to help the user see what's going on.  Turning the ROI on or off should change how the measurement is saved to CSV (should save more pixels if turned off).  It should be possible to save thumbnails in both modes, and see them both graphed together on-screen (ROI spectrum should have a narrower spectral range).

**Comment by rc14193** [comment]
https://github.com/WasatchPhotonics/ENLIGHTEN/pull/42
