### ISSUE TITLE
Laser power control changes

### ISSUE THREAD

**Issue by mzieg** [WasatchPhotonics/ENLIGHTEN#50]
Per internal discussion, please apply the following updates:

- In Wasatch.PY, add is_sml() and is_mml() accessors to SpectrometerSettings.  Both should be false if eeprom.has_laser is false.  If has_laser is true, then is_sml() should be true _iff_ 95 <= eeprom.max_laser_power_mW <= 120.  is_mml() should be true if has_laser and not is_sml().
- In ENLIGHTEN, remove the comboBox_laser_power_unit and replace it with a read-only label.  It should be "milliWatts" if is_mml() and has_laser_power_calibration(), or "percent" otherwise.

**Comment by rc14193** [comment]
https://github.com/WasatchPhotonics/ENLIGHTEN/pull/52
https://github.com/WasatchPhotonics/Wasatch.PY/pull/54
