### ISSUE TITLE
"Export" overwrites each Measurement's "Note" metadata with most recent

### ISSUE THREAD

**Issue by mzieg** [WasatchPhotonics/ENLIGHTEN#56]
I saved 10 spectra, changing the note field on alternating measurements (5 values).  When I did the export, the Note metadata in the aggregate CSV only held the final value (copied into every measurement).  This makes me wonder if other metadata is being similarly trumped?

**Comment by rc14193** [comment]
https://github.com/WasatchPhotonics/ENLIGHTEN/pull/63
