### ISSUE TITLE
Please add Wavecal C4 to CSV metadata

### ISSUE THREAD

**Issue by mzieg** [WasatchPhotonics/ENLIGHTEN#58]
We used to use 3rd-order polynomial but moved to 4th-order, so it would be good to include the 5th coefficient in output files.  (Does not need to be done for "Dash" / row-ordered format.)

**Comment by rc14193** [comment]
https://github.com/WasatchPhotonics/ENLIGHTEN/blob/main/enlighten/Measurement.py#L224

Discussed that solution is already present and sufficient
