### ISSUE TITLE
Apply label template transforms to prefix, suffix and note

### ISSUE THREAD

**Issue by mzieg** [WasatchPhotonics/ENLIGHTEN#65]
We've got this cool new label template system which lets the user create templated macro names like "{integration_time_ms}ms-{gain_db}dB" which are rendered at the time each Measurement is saved, providing customized graph legend, "label" metadata and thumbnail title.

We might as well drop the other shoe and apply the same transforms to prefix, suffix and note fields. I would find this useful myself.

**Comment by rc14193** [comment]
https://github.com/WasatchPhotonics/ENLIGHTEN/pull/67
