### ISSUE TITLE
Revisit Marquee animation in ENLIGHTEN 4.x

### ISSUE THREAD

**Issue by mzieg** [WasatchPhotonics/ENLIGHTEN#92]
The old ENLIGHTEN 3.x Marquee animation was cute in that it shrunk the graph, but didn't affect the controls.  It had the flaw that you couldn't SEE the Marquee on any screen other than Scope, which is why we moved it to a higher frame in ENLIGHTEN 4.  However, now the animation actually moves the buttons on...well, every button on the GUI.  And that's not good.  

We need to decide where to put it where it doesn't move UI controls.  I'd like to keep it "animated" (appearing / disappearing as needed), but without disrupting other screen elements.  I'm leaning toward having it unfold in the upper-right corner, where it would overlay the Help and Light Mode buttons (same place MacOS notifications appear).

**Comment by samiebee43** [comment]
Here is a screenshot that shows the moving buttons.

![i92-original](https://user-images.githubusercontent.com/124081765/216396032-c17385e7-ce42-4dfd-97cb-d15bef4b602d.png)

One solution might be to leave a dedicated space in the UI for the notification bar.

![i92-dedicated](https://user-images.githubusercontent.com/124081765/216395882-43af4cef-695e-4608-ac2e-902c33a66f72.png)

Another option is to squish the nav bar.

![i92-squashlogo](https://user-images.githubusercontent.com/124081765/216395891-2e088239-fd6e-46b3-bc95-93ada60a5e8a.png)

Finally, there is the floating notification option. Which I think is probably the best one. It has the added benefit that the width can be reduced to just cover the text needed.

![i92-floating](https://user-images.githubusercontent.com/124081765/216398929-e0bde55e-0fae-49fd-9fb5-4f93e63ce5a3.png)

**Comment by mzieg** [comment]
Hi Samie, for now I vote for "dedicated space in the UI for the notification bar."  I conceptually like the "floating" alert, but it covers up other buttons.  To me, your first suggestion solves the immediate customer-facing problem while buying us time to play with other display options in-house.

**Comment by samiebee43** [comment]
Pretty sure this is fixed now. Need to confirm if it has been merged to main

**Comment by samiebee43** [comment]
Dedicated space is merged to main and available in 4.0.12 beta.
